import type { Metadata } from "next";
import Head from "next/head";
import Link from "next/link";
import './globals.css'
// import { Inter } from "next/font/google"; 

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">  
      <body>{children}</body>
    </html>
  );
}
